---
- name: install php libraries
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Downloading website files
      get_url:
        url: http://10.2.250.99/site.zip
        dest: /var/www/html
      when: inventory_hostname == vm_name
    - name: unzip fix permissions
      unarchive:
        src: /var/www/html/site.zip
        dest: /var/www/html
        remote_src: yes
      when: inventory_hostname == vm_name
    - name: fix permisssion
      file:
        path: /var/www/html
        owner: apache
        group: apache
      when: inventory_hostname == vm_name

    - name: Download the sql dump
      get_url:
        url: http://10.2.250.99/wp.sql
        dest: /var/www/html
      when: inventory_hostname == vm_name
    - name: restore the database
      mysql_db:
        name: wp
        state: import
        target: /var/www/html/wp.sql
        login_user: root
        login_password: 'P@ssw0rd'
      when: inventory_hostname == vm_name
    - name: change ip address
      template:
        src: ifcfg-ens192.j2
        dest: /etc/sysconfig/network-scripts/ifcfg-ens192
      when: inventory_hostname == vm_name
    - name: restart Network
      service:
        name: network
        state: restarted
      async: 45
      poll: 0
      when: inventory_hostname == vm_name

