---
- name: Generate random password and update root password
  hosts: 192.168.18.3
  gather_facts: yes
  tasks:
    - name: Generate a random password
      set_fact:
        new_password: "{{ lookup('password', '/dev/null length=16') | regex_replace('[^a-zA-Z0-9!@#$%^&*()_+]', '') }}"

    - name: Change the root password
      user:
        name: root
        password: "{{ new_password | password_hash('sha512') }}"
      become: true

    - name: Create a temporary CSV file with password information
      copy:
        content: |
          Hostname,Description,Password
          {{ ansible_hostname }},Root Password,{{ new_password }}
        dest: root_password.csv


    - name: Notify user
      debug:
        msg: "Root password changed and exported to root_password.xlsx"
