---
- name: Change user password
  hosts: all
  become:
  vars:
    username: "root"
    newpassword: "P@ssw0rd"

  tasks:
    - name: Change user password
      user:
        name: "{{ username }}"
        password: "{{ newpassword | password_hash('sha512') }}"
      register: password_change

    - name: Debug output
      debug:
        msg: "Password for user {{ username }} has been changed successfully."
      when: password_change.changed

