---
- name: Change user password
  hosts: all
  become:
  vars:
    username: "root"
    newpassword: "P@ssw0rd"

  tasks:
    - name: Change user password
      user:
        name: "{{ username }}"
        password: "{{ newpassword | password_hash('sha512') }}"
      register: password_change

    - name: Debug output
      debug:
        msg: "Password for user {{ username }} has been changed successfully."
      when: password_change.changed

---
- name: Append root password information to a centralized CSV file
  hosts: all
  become: yes
  vars:
    new_password: "P@ssw0rd"
    csv_file_path: "/tmp/file.csv" 

  tasks:
    - name: Create a temporary csv file with P@ssw0rd information
      copy:
        content: |
          Hostname,Description,Password
          {{ ansible_hostname }},Root Password,{{ new_password }}
        dest: "/tmp/root_password_{{ inventory_hostname }}.csv"

    - name: append temp csv  file on Ansible server
      fetch:
        src: "/tmp/root_password_{{ inventory_hostname }}.csv"
        dest: "/tmp/"
        flat: yes

    - name: append content to the  csv file
      lineinfile:
        path: "{{ csv_file_path }}"
        line: "{{ item }}"
        create: yes
      loop: "{{ lookup('fileglob', '/tmp/root_password_*.csv') }}"

    
