---
- name: install packages using MSI
  hosts: all
  tasks:
   - name: Download the MSI {{ ansible_hostname }}
     win_get_url:
       url: "{{ url }}"
       dest: "{{ dest }}"
   - name: install the MSI {{ ansible_hostname }}
     win_package:
       path: "{{ path }}"
       state: "{{ state }}"
