---
- name: manage win feature
  hosts: all
  tasks:
    - name: Manage windows services on {{ ansible_hostname }}
      win_service:
        name: "{{ service_name }}"
        state: "{{ service_state }}"
